# Neural Networks

## NN test

In [1]:
#imports

import sys
sys.path.insert(1, '/Users/danielalemos/si/src/si/data')
sys.path.insert(1, '/Users/danielalemos/si/src/si/neural_networks')
sys.path.insert(1, '/Users/danielalemos/si/src/si/model_selection')
sys.path.insert(1, '/Users/danielalemos/si/src/si/io')
sys.path.insert(1, '/Users/danielalemos/si/src/si/metrics')

from dataset import Dataset
from layer import Dense, SigmoidActivation, SoftMaxActivation, ReLUActivation, LinearActivation
from nn import NN
from csv_file import read_csv
from split import train_test_split
from cross_entropy import cross_entropy, cross_entropy_derivative
from accuracy import accuracy
from mse import mse, mse_derivative

import numpy as np

In [2]:
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[1],
              [0],
              [0],
              [1]])

dataset = Dataset(X, y, features=['x1', 'x2'], label='X1 XNOR X2')
dataset.to_dataframe()

x1  x2  X1 XNOR X2
0   0   0           1
1   0   1           0
2   1   0           0
3   1   1           1

In [3]:
# weights for Dense Layer 1

w1 = np.array([[0, 0],
               [0, 0]], dtype = np.float64)
               
b1 = np.array([[-30, 10]])

l1 = Dense(input_size = 2, output_size = 2)
#l1.weights = w1
#l1.bias = b1

In [4]:
# weights for Dense Layer 2

w2 = np.array([[0],
               [0]])
               
b2 = np.array([[-10]])

l2 = Dense(input_size = 2, output_size = 1)
#l2.weights = w2
#l2.bias = b2

In [5]:
l1_sg = SigmoidActivation()
l2_sg = SigmoidActivation()

# layers
layers = [l1, l1_sg, l2, l2_sg]

# NN
nn = NN(layers = layers)

In [6]:
nn.fit(dataset = dataset)

In [7]:
nn.predict(dataset = dataset)

array([[0.50080376],
       [0.50079269],
       [0.50079894],
       [0.50078787]])

## Evaluation

#### Exercice 10.3

In [8]:
ds = Dataset.from_random(n_samples = 100, n_features = 32, label = False)
y3 = np.random.randint(0,2,100)
data3 = Dataset(ds.X, y3)
data3.to_dataframe()


0         1         2         3         4         5         6  \
0   0.173262  0.510004  0.025872  0.270320  0.673003  0.546276  0.336808   
1   0.245089  0.960289  0.169962  0.677102  0.577526  0.459999  0.338347   
2   0.593714  0.623044  0.328341  0.804983  0.895324  0.638912  0.139159   
3   0.993715  0.396111  0.138665  0.705301  0.690583  0.032972  0.730636   
4   0.710436  0.922676  0.136730  0.663715  0.166652  0.971098  0.142190   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.934609  0.327122  0.410029  0.358404  0.227953  0.093076  0.967298   
96  0.696832  0.869901  0.340870  0.871965  0.653317  0.752738  0.686823   
97  0.053114  0.650698  0.319260  0.121723  0.846643  0.641169  0.530481   
98  0.564233  0.381568  0.335620  0.776913  0.917523  0.261069  0.103042   
99  0.851761  0.196052  0.972042  0.674955  0.837064  0.500732  0.136891   

           7         8         9  ...        23        24        25        26  \
0   0.240272  0.892574  0.675447  ...  0.037528  0.137071  0.795580  0.690224   
1   0.979044  0.626540  0.604647  ...  0.405487  0.275263  0.453397  0.867572   
2   0.603452  0.738271  0.571468  ...  0.121299  0.415613  0.591132  0.854576   
3   0.221075  0.522039  0.772814  ...  0.394643  0.981694  0.779299  0.041955   
4   0.408353  0.189407  0.410910  ...  0.380540  0.337918  0.956155  0.883922   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  0.406343  0.483403  0.039541  ...  0.031995  0.133877  0.883631  0.502690   
96  0.426492  0.607591  0.558094  ...  0.802689  0.611652  0.007788  0.602334   
97  0.836156  0.763378  0.032380  ...  0.891231  0.484559  0.181909  0.030990   
98  0.879741  0.796631  0.460674  ...  0.219272  0.996030  0.805705  0.673090   
99  0.003142  0.194259  0.798008  ...  0.715267  0.033517  0.929889  0.284995   

          27        28        29        30        31  NaN  
0   0.052487  0.307014  0.436502  0.646171  0.600970    0  
1   0.515206  0.218868  0.994319  0.758804  0.275882    0  
2   0.224828  0.156292  0.574069  0.842134  0.244224    0  
3   0.751943  0.109690  0.352958  0.328811  0.427275    0  
4   0.612385  0.851711  0.936938  0.881930  0.677962    1  
..       ...       ...       ...       ...       ...  ...  
95  0.747915  0.385336  0.698725  0.057890  0.726066    0  
96  0.544221  0.754870  0.974863  0.582875  0.588243    1  
97  0.883692  0.759439  0.804192  0.898319  0.309087    1  
98  0.266832  0.122689  0.312924  0.608554  0.374224    1  
99  0.017150  0.371621  0.232890  0.862475  0.424181    0  

[100 rows x 33 columns]

In [9]:
layer1_3 = Dense(input_size = 32, output_size = 32)
layer2_3 = Dense(input_size = 32, output_size = 16)
layer3_3 = Dense(input_size = 16, output_size = 1)

In [10]:
layer1_3_sg = SigmoidActivation ()
layer2_3_sg = SigmoidActivation ()
layer3_3_sg = SigmoidActivation ()
layers3 = [layer1_3, layer1_3_sg,layer2_3, layer2_3_sg,layer3_3, layer3_3_sg]

In [11]:
nn_model_3 = NN(layers = layers3)
nn_model_3.fit(data3)
pred = nn_model_3.predict(data3)
pred

array([[0.37705784],
       [0.37706108],
       [0.37706276],
       [0.37706412],
       [0.3770655 ],
       [0.37706395],
       [0.37705904],
       [0.37706996],
       [0.37705944],
       [0.3770635 ],
       [0.37705663],
       [0.37706489],
       [0.37706083],
       [0.37706039],
       [0.37705882],
       [0.37706297],
       [0.37706326],
       [0.37705908],
       [0.37706143],
       [0.37706299],
       [0.37706144],
       [0.37706163],
       [0.37705768],
       [0.37705593],
       [0.37706336],
       [0.3770601 ],
       [0.37706322],
       [0.37706077],
       [0.37706208],
       [0.37706425],
       [0.37706059],
       [0.37706448],
       [0.37706405],
       [0.37706194],
       [0.37706198],
       [0.37706349],
       [0.37705922],
       [0.37705635],
       [0.37706267],
       [0.37706296],
       [0.37706406],
       [0.37706353],
       [0.3770629 ],
       [0.37706146],
       [0.37706364],
       [0.37706095],
       [0.37706195],
       [0.377

In [12]:
pred = np.where(pred > 0.5, 1, 0).reshape(1,-1)

In [13]:
score = accuracy(data3.y,pred)
print(score)

0.63


#### Exercice 10.4

In [14]:
y4 = np.random.randint(0, 3, 100)
data4 = Dataset(ds.X, y4)
data4.to_dataframe()

0         1         2         3         4         5         6  \
0   0.173262  0.510004  0.025872  0.270320  0.673003  0.546276  0.336808   
1   0.245089  0.960289  0.169962  0.677102  0.577526  0.459999  0.338347   
2   0.593714  0.623044  0.328341  0.804983  0.895324  0.638912  0.139159   
3   0.993715  0.396111  0.138665  0.705301  0.690583  0.032972  0.730636   
4   0.710436  0.922676  0.136730  0.663715  0.166652  0.971098  0.142190   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.934609  0.327122  0.410029  0.358404  0.227953  0.093076  0.967298   
96  0.696832  0.869901  0.340870  0.871965  0.653317  0.752738  0.686823   
97  0.053114  0.650698  0.319260  0.121723  0.846643  0.641169  0.530481   
98  0.564233  0.381568  0.335620  0.776913  0.917523  0.261069  0.103042   
99  0.851761  0.196052  0.972042  0.674955  0.837064  0.500732  0.136891   

           7         8         9  ...        23        24        25        26  \
0   0.240272  0.892574  0.675447  ...  0.037528  0.137071  0.795580  0.690224   
1   0.979044  0.626540  0.604647  ...  0.405487  0.275263  0.453397  0.867572   
2   0.603452  0.738271  0.571468  ...  0.121299  0.415613  0.591132  0.854576   
3   0.221075  0.522039  0.772814  ...  0.394643  0.981694  0.779299  0.041955   
4   0.408353  0.189407  0.410910  ...  0.380540  0.337918  0.956155  0.883922   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  0.406343  0.483403  0.039541  ...  0.031995  0.133877  0.883631  0.502690   
96  0.426492  0.607591  0.558094  ...  0.802689  0.611652  0.007788  0.602334   
97  0.836156  0.763378  0.032380  ...  0.891231  0.484559  0.181909  0.030990   
98  0.879741  0.796631  0.460674  ...  0.219272  0.996030  0.805705  0.673090   
99  0.003142  0.194259  0.798008  ...  0.715267  0.033517  0.929889  0.284995   

          27        28        29        30        31  NaN  
0   0.052487  0.307014  0.436502  0.646171  0.600970    0  
1   0.515206  0.218868  0.994319  0.758804  0.275882    1  
2   0.224828  0.156292  0.574069  0.842134  0.244224    1  
3   0.751943  0.109690  0.352958  0.328811  0.427275    2  
4   0.612385  0.851711  0.936938  0.881930  0.677962    1  
..       ...       ...       ...       ...       ...  ...  
95  0.747915  0.385336  0.698725  0.057890  0.726066    0  
96  0.544221  0.754870  0.974863  0.582875  0.588243    0  
97  0.883692  0.759439  0.804192  0.898319  0.309087    2  
98  0.266832  0.122689  0.312924  0.608554  0.374224    2  
99  0.017150  0.371621  0.232890  0.862475  0.424181    2  

[100 rows x 33 columns]

In [15]:
layer1_4 = Dense(input_size = 32, output_size = 32)
layer2_4 = Dense(input_size = 32, output_size = 16)
layer3_4 = Dense(input_size = 16, output_size = 3)

In [16]:
layer1_4_sg = SigmoidActivation ()
layer2_4_sg = SigmoidActivation ()
layer3_4_sf = SoftMaxActivation ()
layers4 = [layer1_4, layer1_4_sg,layer2_4, layer2_4_sg,layer3_4, layer3_4_sf]

In [17]:
nn_model_4 = NN(layers = layers4)
nn_model_4.fit(data4)
probs = nn_model_4.predict(data4)

In [18]:
pred = []
for elem in probs:
    pred += [np.argmax(elem)]
print(pred)

[0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1]


In [19]:
score = accuracy(y4,pred)
print(score)

0.4


#### Exercice 10.5

In [20]:
y5 = np.random.randn(100)
data5 = Dataset(ds.X, y5)
data5.to_dataframe()

0         1         2         3         4         5         6  \
0   0.173262  0.510004  0.025872  0.270320  0.673003  0.546276  0.336808   
1   0.245089  0.960289  0.169962  0.677102  0.577526  0.459999  0.338347   
2   0.593714  0.623044  0.328341  0.804983  0.895324  0.638912  0.139159   
3   0.993715  0.396111  0.138665  0.705301  0.690583  0.032972  0.730636   
4   0.710436  0.922676  0.136730  0.663715  0.166652  0.971098  0.142190   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.934609  0.327122  0.410029  0.358404  0.227953  0.093076  0.967298   
96  0.696832  0.869901  0.340870  0.871965  0.653317  0.752738  0.686823   
97  0.053114  0.650698  0.319260  0.121723  0.846643  0.641169  0.530481   
98  0.564233  0.381568  0.335620  0.776913  0.917523  0.261069  0.103042   
99  0.851761  0.196052  0.972042  0.674955  0.837064  0.500732  0.136891   

           7         8         9  ...        23        24        25        26  \
0   0.240272  0.892574  0.675447  ...  0.037528  0.137071  0.795580  0.690224   
1   0.979044  0.626540  0.604647  ...  0.405487  0.275263  0.453397  0.867572   
2   0.603452  0.738271  0.571468  ...  0.121299  0.415613  0.591132  0.854576   
3   0.221075  0.522039  0.772814  ...  0.394643  0.981694  0.779299  0.041955   
4   0.408353  0.189407  0.410910  ...  0.380540  0.337918  0.956155  0.883922   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  0.406343  0.483403  0.039541  ...  0.031995  0.133877  0.883631  0.502690   
96  0.426492  0.607591  0.558094  ...  0.802689  0.611652  0.007788  0.602334   
97  0.836156  0.763378  0.032380  ...  0.891231  0.484559  0.181909  0.030990   
98  0.879741  0.796631  0.460674  ...  0.219272  0.996030  0.805705  0.673090   
99  0.003142  0.194259  0.798008  ...  0.715267  0.033517  0.929889  0.284995   

          27        28        29        30        31       NaN  
0   0.052487  0.307014  0.436502  0.646171  0.600970  0.006897  
1   0.515206  0.218868  0.994319  0.758804  0.275882  0.306498  
2   0.224828  0.156292  0.574069  0.842134  0.244224  0.909681  
3   0.751943  0.109690  0.352958  0.328811  0.427275  0.995093  
4   0.612385  0.851711  0.936938  0.881930  0.677962 -0.649413  
..       ...       ...       ...       ...       ...       ...  
95  0.747915  0.385336  0.698725  0.057890  0.726066  1.016794  
96  0.544221  0.754870  0.974863  0.582875  0.588243  0.164717  
97  0.883692  0.759439  0.804192  0.898319  0.309087 -1.672645  
98  0.266832  0.122689  0.312924  0.608554  0.374224 -2.043708  
99  0.017150  0.371621  0.232890  0.862475  0.424181 -0.249813  

[100 rows x 33 columns]

In [21]:
layer1_5 = Dense(input_size = 32, output_size = 32)
layer2_5 = Dense(input_size = 32, output_size = 16)
layer3_5 = Dense(input_size = 16, output_size = 1)

In [22]:
layer1_5_rl = ReLUActivation ()
layer2_5_rl = ReLUActivation ()
layer3_5_ln = LinearActivation ()
layers5 = [layer1_5, layer1_5_rl,layer2_5, layer2_5_rl,layer3_5, layer3_5_ln]

In [23]:
nn_model_5 = NN(layers = layers5)
nn_model_5.fit(data5)
pred = nn_model_5.predict(data5)
pred

array([[0.23037564],
       [0.23039687],
       [0.23038741],
       [0.23034668],
       [0.23041977],
       [0.23039241],
       [0.23038104],
       [0.2303965 ],
       [0.23038936],
       [0.23036889],
       [0.23034644],
       [0.23039239],
       [0.23039522],
       [0.23040979],
       [0.23040122],
       [0.2303758 ],
       [0.23037175],
       [0.23038666],
       [0.23036231],
       [0.2303705 ],
       [0.23037809],
       [0.23036817],
       [0.23040076],
       [0.23040848],
       [0.23044358],
       [0.23040726],
       [0.2303661 ],
       [0.23037641],
       [0.23038338],
       [0.23038276],
       [0.23036346],
       [0.23041937],
       [0.23038511],
       [0.23034153],
       [0.23039473],
       [0.23037158],
       [0.23040308],
       [0.23039707],
       [0.2303641 ],
       [0.2303902 ],
       [0.23038414],
       [0.23035698],
       [0.2303824 ],
       [0.23038982],
       [0.23041743],
       [0.23038428],
       [0.23035977],
       [0.230

In [24]:
pred = np.where(pred > 0.5, 1, 0).reshape(1,-1)

In [25]:
score = accuracy(data5.y,pred)
print(score)

0.0


#### Exercice 12.2

In [26]:
# datasets
breast_bin = read_csv('/Users/danielalemos/si/datasets/breast-bin.csv', features=False, label=True)
cpu = read_csv('/Users/danielalemos/si/datasets/cpu.csv', sep = ',', features = True, label = True)

In [27]:
breast_bin.y[:20]

array([0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0.])

Binary problem

In [28]:
# standardization
from sklearn.preprocessing import StandardScaler
breast_bin.X = StandardScaler().fit_transform(breast_bin.X)
breast_bin.X

array([[ 0.20885295, -0.69912815, -0.74242297, ..., -1.0000359 ,
        -0.61132565, -0.34418721],
       [-0.8578253 , -0.69912815, -0.74242297, ..., -0.58991542,
        -0.61132565, -0.34418721],
       [-0.8578253 , -0.69912815, -0.74242297, ..., -0.17979494,
        -0.61132565, -0.34418721],
       ...,
       [ 0.20885295, -0.37139715, -0.40592217, ..., -1.0000359 ,
        -0.61132565,  0.23892607],
       [-0.8578253 , -0.04366616, -0.40592217, ..., -0.17979494,
        -0.61132565, -0.34418721],
       [ 0.91997179,  0.93952681,  0.94008103, ...,  1.46068699,
        -0.61132565, -0.34418721]])

In [29]:
breast_bin_train, breast_bin_test = train_test_split(breast_bin, test_size = 0.3)
breast_bin_test.y

array([0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0.,
       1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1.,
       0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0.])

In [30]:
print(breast_bin_train.shape())
print(breast_bin_test.shape())

(489, 9)
(209, 9)


In [31]:
l1_bin = Dense(input_size = 9, output_size = 5)
l2_bin = Dense(input_size = 5, output_size = 1)


l1_bin_relu = ReLUActivation()
l2_bin_sig = SigmoidActivation()

layers = [l1_bin, l1_bin_relu, l2_bin, l2_bin_sig]

model_bin = NN(layers=layers, loss = cross_entropy, loss_derivative = cross_entropy_derivative, verbose = True)

In [32]:
model_bin.fit(dataset = breast_bin_train)

Epoch 1/1000 - cost: 0.22815562885837742
Epoch 2/1000 - cost: 0.2640331677462615
Epoch 3/1000 - cost: 0.29028912502162174
Epoch 4/1000 - cost: 0.30778612420769147
Epoch 5/1000 - cost: 0.3157362988402742
Epoch 6/1000 - cost: 0.30760689346156017
Epoch 7/1000 - cost: 0.2648755424980361
Epoch 8/1000 - cost: 0.17153320917458806
Epoch 9/1000 - cost: 0.10187387377038798
Epoch 10/1000 - cost: 0.08316725727412624
Epoch 11/1000 - cost: 0.07421268212086037
Epoch 12/1000 - cost: 0.06852242986218338
Epoch 13/1000 - cost: 0.06445724998029248
Epoch 14/1000 - cost: 0.061354554925799776
Epoch 15/1000 - cost: 0.05888273480502156
Epoch 16/1000 - cost: 0.05685110352626796
Epoch 17/1000 - cost: 0.055140072791142775
Epoch 18/1000 - cost: 0.053670520006423736
Epoch 19/1000 - cost: 0.05238711862523111
Epoch 20/1000 - cost: 0.05125301881260607
Epoch 21/1000 - cost: 0.050241732614674156
Epoch 22/1000 - cost: 0.04933026318525133
Epoch 23/1000 - cost: 0.048501749415505474
Epoch 24/1000 - cost: 0.04774188677521353

In [33]:
pred = model_bin.predict(breast_bin_test)
pred

array([[0.74394817],
       [0.99999359],
       [0.09214094],
       [0.01686973],
       [0.01536738],
       [0.01536738],
       [0.99949105],
       [0.01536738],
       [0.01536738],
       [0.72247129],
       [0.01536738],
       [0.99132695],
       [0.9988987 ],
       [0.99511113],
       [0.03031438],
       [0.01536738],
       [0.01536738],
       [0.05899726],
       [0.99960918],
       [0.01536738],
       [0.01536738],
       [0.99982902],
       [0.01536738],
       [0.99999984],
       [0.99999976],
       [0.30054366],
       [0.01536738],
       [0.01536738],
       [0.01536738],
       [0.01536738],
       [0.99999993],
       [0.03604551],
       [0.99999503],
       [0.01536738],
       [0.01536738],
       [0.01536738],
       [0.01536738],
       [0.01536738],
       [0.99991509],
       [0.99999972],
       [0.05293902],
       [0.01536738],
       [0.99999728],
       [0.08067035],
       [0.02193672],
       [0.99946804],
       [0.99999539],
       [0.015

In [34]:
pred = np.where(pred > 0.5, 1, 0).reshape(1,-1)
print(pred)

[[1 1 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0 0
  0 0 1 1 0 0 1 0 0 1 1 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 1 0 0 1 0 0 1 0 0 0
  0 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 1 0 1 1 0 0 0 0
  0 1 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 0 1 0
  0 0 0 0 1 1 0 1 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1
  1 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0]]


In [35]:
score = accuracy(breast_bin_test.y,pred)
print(score)

0.9760765550239234


#### Exercice 12.3

In [36]:
cpu.y[:20]

array([ 198,  269,  220,  172,  132,  318,  367,  489,  636, 1144,   38,
         40,   92,  138,   10,   35,   19,   28,   31,  120])

Regression problem

In [37]:
cpu.X = StandardScaler().fit_transform(cpu.X)
cpu.X

array([[-0.30358614, -0.67502598, -0.49546221,  5.69420785,  1.66198873,
         4.23103334],
       [-0.67332952,  1.32629082,  1.72704937,  0.16762947,  0.48550899,
         0.52947875],
       [-0.67332952,  1.32629082,  1.72704937,  0.16762947,  0.48550899,
         0.52947875],
       ...,
       [-0.30358614, -0.2243162 , -0.32449978, -0.62188173, -0.39685082,
        -0.16456273],
       [ 1.06369405, -0.60886675, -0.32449978,  0.16762947, -0.69097076,
        -0.70437278],
       [ 1.06369405, -0.48275071, -0.66642464, -0.62188173, -0.69097076,
        -0.70437278]])

In [38]:
cpu_train, cpu_test = train_test_split(cpu, test_size = 0.3)
cpu_test.y

array([ 274,   30,   22,  915,   16,  326,   72,    6, 1144,  208,   65,
        130,   52,   45,   35,   36,   51,   31,  100,  132,   50,   60,
        110,   18,   11,   50,   69,   27,   19,   41,  248,   32,   45,
         26,   16,   26,   67,  465,   38,   17,  307,   34,  214,  465,
       1150,   32,  510,   40,   24,   71,   23,   11,   24,   27,  120,
         54,   40,   17,  259,  318,   93,   71])

In [39]:
print(cpu_train.shape())
print(cpu_test.shape())

(147, 6)
(62, 6)


In [40]:
l1_reg = Dense(input_size = 6, output_size = 3)
l2_reg = Dense(input_size = 3, output_size = 1)


l1_reg_relu = ReLUActivation()

layers = [l1_reg, l1_reg_relu, l2_reg]

model_reg = NN(layers = layers, loss = mse, loss_derivative = mse_derivative, verbose = True)

In [41]:
model_reg.fit(dataset = cpu_train)

Epoch 1/1000 - cost: 9544.953685474411
Epoch 2/1000 - cost: 9466.558767603936
Epoch 3/1000 - cost: 9389.543379949706
Epoch 4/1000 - cost: 9312.772245283873
Epoch 5/1000 - cost: 9228.638223059983
Epoch 6/1000 - cost: 9085.12284788491
Epoch 7/1000 - cost: 8537.641589658117
Epoch 8/1000 - cost: 5739.7979474317945
Epoch 9/1000 - cost: 1353.0404974381129
Epoch 10/1000 - cost: 2279.8149095959852
Epoch 11/1000 - cost: 4157.293982319844
Epoch 12/1000 - cost: 8999.847601796235
Epoch 13/1000 - cost: 8775.871943106456
Epoch 14/1000 - cost: 8563.79903139631
Epoch 15/1000 - cost: 8150.3426817866475
Epoch 16/1000 - cost: 6115.81847445265
Epoch 17/1000 - cost: 1399.790385304059
Epoch 18/1000 - cost: 1571.2341449796468
Epoch 19/1000 - cost: 4441.749646353441
Epoch 20/1000 - cost: 2130.3720235562023
Epoch 21/1000 - cost: 6300.14606815405
Epoch 22/1000 - cost: 891.0843607659427
Epoch 23/1000 - cost: 1336.391704223484
Epoch 24/1000 - cost: 3528.5482147662865
Epoch 25/1000 - cost: 2926.5353151238564
Epoch

In [42]:
pred = model_reg.predict(cpu_test)
pred

array([[ 302.91298324],
       [  35.26737324],
       [  34.19686487],
       [ 630.74308931],
       [  34.19686487],
       [ 317.64759214],
       [  44.34687522],
       [  43.77619013],
       [1276.45737204],
       [ 293.60343785],
       [  78.87948442],
       [  81.50836869],
       [  34.19686487],
       [  41.33219409],
       [  34.35903339],
       [  34.19686487],
       [ 134.49246891],
       [  34.19686487],
       [ 183.58919312],
       [  98.94098499],
       [  34.19686487],
       [  63.95150838],
       [ 141.72370195],
       [  34.19686487],
       [  34.19686487],
       [  40.20552366],
       [  37.66487541],
       [  34.19686487],
       [  36.55060932],
       [ 110.11195884],
       [ 369.22660133],
       [  34.19686487],
       [  60.34944728],
       [  34.43769558],
       [  34.19686487],
       [  66.52639618],
       [  73.56273767],
       [ 569.95184146],
       [ 125.92750117],
       [  39.04668938],
       [ 506.7529678 ],
       [  48.829

In [43]:
from sklearn.metrics import r2_score

r2_score(cpu_test.y, pred)

0.8554298370419356